<p>O código abaixo retornará um erro, listas em Python não permitem operações com diferentes tipos</p>

In [ ]:
sccp_important_years = [1910, 1914, 1954, 1977, 1990, 2000, 2012]
sccp_important_sccp_years * 1.5

O NumPy permite operações matemáticas com diferentes tipos de dado

In [3]:
import numpy as np

sccp_important_years_as_array = np.array([1910, 1914, 1954, 1977, 1990, 2000, 2012])
sccp_important_years_as_array * 1.5

#output
# array([2865. , 2871. , 2931. , 2965.5, 2985. , 3000. , 3018. ])

array([2865. , 2871. , 2931. , 2965.5, 2985. , 3000. , 3018. ])

Uma outra diferença é que ao contrário das listas em Python um Array no NumPy é homogêneo, ou seja, possui apenas um tipo, este é um dos motivos para o NumPy ter uma melhor performance do que a manipulação de listas em Python.

No exemplo abaixo vamos criar um Array com diferentes tipos no NumPy e ver como ele converte isso para um dado homogêneo:

In [4]:
np.array([1, 2.3, 4, 5])

array([1. , 2.3, 4. , 5. ])

No exemplo acima podemos notar que o NumPy converteu os nossos valores inteiros para valores com ponto flutuante, isso acontece por que quando o NumPy recebe uma lista com diferentes tipos, ele vai converter todos os tipos da lista para o tipo mais genérico.

Se fizessemos uma lista "hierarquica" do mais genérico ao menos considerando os dados do tipo texto, ponto flutuante e inteiro, temos a seguinte ordem:

1º Texto (str)
2º Ponto Flutuante (float)
3º Inteiro (int)

O raciocinio aqui é, eu consigo converter qualquer dado do tipo inteiro ou ponto flutuante para um texto, mas o mesmo não ocorre de informa inversa. Em resumo se uma lista tiver diferentes tipos de dados o NumPy vai converter todos os dados para o tipo mais genérico.

In [14]:
print(np.array([1, 2, 3, 4, 5, '6'])) # todos passam a ser do tipo texto
print(np.array([1, 2, 3, 4, 5, 6, 7.0])) # todos passam a ser do tipo ponto flutuante
print(np.array([1, 2.1, '3']))  # todos passsam a ser di tipo texto
print(np.array([1, 2, 3, 4, 5])) # todos são inteiros

['1' '2' '3' '4' '5' '6']
[1. 2. 3. 4. 5. 6. 7.]
['1' '2.1' '3']
[1 2 3 4 5]


Listas em Python não fazem tornam nosso dado homôgeneo, uma vez que ela tenha diferentes valores, isso será prevalecido

In [15]:
print([1, 2, 3, '4']) # [0:3] --> inteir, apenas o ultimo elemento  prevalece como 'texto'

[1, 2, 3, '4']
