Importando NumPy

In [2]:
import numpy as np

Criando lista com 5 elementos

In [4]:
list_with_5_elements = np.arange(5)
list_with_5_elements

array([0, 1, 2, 3, 4])

Criando uma lista com indice inicial e final customizados (inicial é incluído no array o final não)

In [7]:
llist_starts_at_7_ends_15 = np.arange(5, 16)
llist_starts_at_7_ends_15

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Criando uma lista com indice inicial e final customizados e aplicando uma regra entre cada indice

In [8]:
just_even_numbers_between_0_and_50 = np.arange(0, 50, 2)
just_even_numbers_between_0_and_50

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

Criando uma matriz com o arange

In [26]:
rows_amount = 2
columns_amount = 3

arr = np.arange(1, 7).reshape(rows_amount, columns_amount)
arr

array([[1, 2, 3],
       [4, 5, 6]])

Obtendo total de linhas e colunas da nossa matriz

In [27]:
arr.shape

(2, 3)