# Acessando dados de uma matriz

In [18]:
import numpy as np

m = np.arange(20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Acessar dados de uma matriz segue os mesmos principios de acessar os dados de um array, abaixo desejo acessar o 3º elemento da linha 4.

~~~python
m[3] # me retornaria [15, 16, 17, 18, 19]
# Dentro da linha retornada desejo obter o ultimo elemento, em um array de 5 itens o elemento de nº 4 será o ultimo, logo preciso de:
m[3][4]
~~~

In [20]:
last_item_of_last_row = m[3][4]
last_item_of_last_row

19

# Filtrando dados de uma matriz com uma condição

In [21]:
just_numbers_bigger_than_9 = m[m > 9]
just_numbers_bigger_than_9

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Filtrando dados de uma matriz com mais de uma condição

In [29]:
m[(m > 7) & (m < 15)]

array([ 8,  9, 10, 11, 12, 13, 14])