## np.where()

Retorna os índices dos elementos de um array que correspondem a um determinado filtro

In [2]:
import numpy as np

In [46]:
SCCP = 35_000_000
SFC  = 8_000_000
SPFC = 22_000_000
SEP  = 15_000_000

supporters_amount_sp = np.array([SCCP, SFC, SPFC, SEP])

In [22]:
avg_supporters = np.mean(supporters_amount_sp) # Média
avg_supporters

20000000.0

In [45]:
index_of_clubs_with_amount_supporters_bigger_than_avg = np.where(supporters_amount_sp > avg_supporters)
index_of_clubs_with_amount_supporters_bigger_than_avg

(array([0, 2]),)

O `np.where()` **retorna os indices** dos elementos que correspondem a busca.

Podemos verificar todos estes valores na lista original passando todos os indices de uma unica vez:

In [47]:
supporters_amount_sp[index_of_clubs_with_amount_supporters_bigger_than_avg]

array([35000000, 22000000])

### É possível obtermos os valores filtrando diretamente no array também:

In [48]:
supporters_amount_sp[supporters_amount_sp > avg_supporters]

array([35000000, 22000000])

In [49]:
### Avançando com o np.where()

### Podemos criar um novo array com valores customizados quando atendem ou não a condicional:

In [52]:
np.where(supporters_amount_sp > avg_supporters, 'Acima da média', 'Abaixo da média')

array(['Acima da média', 'Abaixo da média', 'Acima da média',
       'Abaixo da média'], dtype='<U15')

### Podemos usar o iterador na nossa condicional:

In [70]:
clubs_calc =  np.where(supporters_amount_sp < avg_supporters, supporters_amount_sp * 1.1, supporters_amount_sp)

print(supporters_amount_sp)
print(clubs_calc)

[35000000  8000000 22000000 15000000]
[35000000.  8800000. 22000000. 16500000.]


### Multiplas condicionais

In [74]:
np.where((supporters_amount_sp > 30_000_000) & (supporters_amount_sp < 40_000_000) ) # Ressaltando que o que será retornado é o índice

(array([0]),)

In [75]:
np.where((supporters_amount_sp < 10_000_000) | (supporters_amount_sp > 30_000_000) ) # Ressaltando que o que será retornado é o índice


(array([0, 1]),)